"""User-reviewed screenshot clues with official CF metadata; rating 0 denotes unrated."""

SEARCH_CLUES = [{'key': '2246E@search',
  'title': 'lce4113 and Security Game',
  'rating': 2600,
  'contest_time': 1783866900,
  'round_type': 'Div. 2',
  'source_url': 'https://codeforces.com/contest/2246/problem/E',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2246E-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2246, 'E', 1108, 'Div. 2')]},
 {'key': '2170C@search',
  'title': 'Quotient and Remainder',
  'rating': 1300,
  'contest_time': 1764340500,
  'round_type': 'Edu',
  'source_url': 'https://codeforces.com/contest/2170/problem/C',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2170C-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2170, 'C', 185, 'Edu')]},
 {'key': '2169B@search',
  'title': 'Drifting Away',
  'rating': 1100,
  'contest_time': 1763130900,
  'round_type': 'Edu',
  'source_url': 'https://codeforces.com/contest/2169/problem/B',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2169B-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2169, 'B', 184, 'Edu')]},
 {'key': '2201C@search',
  'title': 'Rigged Bracket Sequence',
  'rating': 2000,
  'contest_time': 1771857300,
  'round_type': 'Div. 1',
  'source_url': 'https://codeforces.com/contest/2201/problem/C',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2201C-search.jpg',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2201, 'C', 1082, 'Div. 1'), (2202, 'E', 1082, 'Div. 2')]},
 {'key': '2180B@search',
  'title': 'Ashmal',
  'rating': 800,
  'contest_time': 1766154900,
  'round_type': 'Div. 1 + Div. 2',
  'source_url': 'https://codeforces.com/contest/2180/problem/B',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2180B-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2180, 'B', 31, 'Div. 1 + Div. 2')]},
 {'key': '2192D@search',
  'title': 'Cost of Tree',
  'rating': 1800,
  'contest_time': 1771684500,
  'round_type': 'Div. 2',
  'source_url': 'https://codeforces.com/contest/2192/problem/D',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2192D-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2192, 'D', 1081, 'Div. 2')]},
 {'key': '2164D@search',
  'title': 'Copy String',
  'rating': 1800,
  'contest_time': 1762439700,
  'round_type': 'Div. 1 + Div. 2',
  'source_url': 'https://codeforces.com/contest/2164/problem/D',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2164D-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2164, 'D', 30, 'Div. 1 + Div. 2')]},
 {'key': '2169D2@search',
  'title': 'Removal of a Sequence (Hard Version)',
  'rating': 2100,
  'contest_time': 1763130900,
  'round_type': 'Edu',
  'source_url': 'https://codeforces.com/contest/2169/problem/D2',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2169D2-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2169, 'D1', 184, 'Edu'), (2169, 'D2', 184, 'Edu')]},
 {'key': '2161C@search',
  'title': 'Loyalty',
  'rating': 1200,
  'contest_time': 1761842100,
  'round_type': 'Div. 1 + Div. 2',
  'source_url': 'https://codeforces.com/contest/2161/problem/C',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2161C-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2161, 'C', 5, 'Div. 1 + Div. 2')]},
 {'key': '2122D@search',
  'title': 'Traffic Lights',
  'rating': 2400,
  'contest_time': 1752935700,
  'round_type': 'Div. 1 + Div. 2',
  'source_url': 'https://codeforces.com/contest/2122/problem/D',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2122D-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2122, 'D', 1038, 'Div. 1 + Div. 2')]},
 {'key': '2156E@search',
  'title': 'Best Time to Buy and Sell Stock',
  'rating': 2500,
  'contest_time': 1761316500,
  'round_type': 'Div. 2',
  'source_url': 'https://codeforces.com/contest/2156/problem/E',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2156E-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2156, 'E', 1061, 'Div. 2')]},
 {'key': '2137G@search',
  'title': 'Cry Me a River',
  'rating': 2200,
  'contest_time': 1757255700,
  'round_type': 'Div. 3',
  'source_url': 'https://codeforces.com/contest/2137/problem/G',
  'clue': 'Two separately cropped operation descriptions.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2137G-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2137, 'G', 1047, 'Div. 3')]},
 {'key': '2225C@search',
  'title': 'Red-Black Pairs',
  'rating': 1100,
  'contest_time': 1776782100,
  'round_type': 'Edu',
  'source_url': 'https://codeforces.com/contest/2225/problem/C',
  'clue': 'The cells in each pair have the same color and share a side.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2225C-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2225, 'C', 189, 'Edu')]},
 {'key': '2124E@search',
  'title': 'Make it Zero',
  'rating': 2100,
  'contest_time': 1751812500,
  'round_type': 'Div. 1 + Div. 2',
  'source_url': 'https://codeforces.com/contest/2124/problem/E',
  'clue': 'A cropped operation heading and equality of two partial sums.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2124E-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2124, 'E', 1036, 'Div. 1 + Div. 2')]},
 {'key': '2127A@search',
  'title': 'Mix Mex Max',
  'rating': 800,
  'contest_time': 1754577300,
  'round_type': 'Div. 1 + Div. 2',
  'source_url': 'https://codeforces.com/contest/2127/problem/A',
  'clue': 'Three mex, maximum and minimum equalities from the sample explanation.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2127A-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2127, 'A', 1, 'Div. 1 + Div. 2')]},
 {'key': '2146D2@search',
  'title': 'Max Sum OR (Hard Version)',
  'rating': 2000,
  'contest_time': 1758465300,
  'round_type': 'Div. 2',
  'source_url': 'https://codeforces.com/contest/2146/problem/D2',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2146D2-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2146, 'D2', 1052, 'Div. 2')]},
 {'key': '2168C@search',
  'title': 'Intercepting Butterflies',
  'rating': 0,
  'contest_time': 1762180500,
  'round_type': 'Testing',
  'source_url': 'https://codeforces.com/contest/2168/problem/C',
  'clue': 'First run and second run in a communication sample explanation.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2168C-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2168, 'C', 20, 'Testing')]},
 {'key': '2193H@search',
  'title': 'Remove the Grail Tree',
  'rating': 2400,
  'contest_time': 1769351700,
  'round_type': 'Div. 3',
  'source_url': 'https://codeforces.com/contest/2193/problem/H',
  'clue': 'User-reviewed statement screenshot fragment.',
  'clue_kind': 'image',
  'image_path': 'static/questions/2193H-search.png',
  'brain': 1,
  'open_mode': 0,
  'aliases': [(2193, 'H', 1076, 'Div. 3')]}]
