"""Curated seed questions.

The clue text is an original, title-free restatement of each public problem.  It
is deliberately long enough to uniquely identify a problem, while avoiding the
answer-bearing title and contest metadata.
"""

SEED_QUESTIONS = [
    {
        "key": "1328A",
        "title": "Divisibility Problem",
        "rating": 800,
        "contest_time": 1585233300,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1328/problem/A",
        "clue": "You are given two positive integers a and b. In one move you may increase a by 1. Find the minimum number of moves needed to make a divisible by b. Each test contains many independent pairs; both values are at most 10^9.",
        "aliases": [(1328, "A", 629, "Div. 3")],
    },
    {
        "key": "1547C",
        "title": "Pair Programming",
        "rating": 1100,
        "contest_time": 1625927700,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1547/problem/C",
        "clue": "Two programmers made separate logs of changes to the same file. A zero in a log adds a new line to the file; a positive number x edits line x and is valid only when x is not greater than the current number of lines. Merge both logs without changing the order inside either log, or report that no valid merge exists.",
        "aliases": [(1547, "C", 731, "Div. 3")],
    },
    {
        "key": "1729C",
        "title": "Jumping on Tiles",
        "rating": 1100,
        "contest_time": 1662993300,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1729/problem/C",
        "clue": "A row of tiles is described by a lowercase string. The price of a tile equals its letter position in the alphabet. Starting at the first tile, reach the last tile; the cost of a jump is the absolute difference between the prices of its endpoints. Minimize total cost, then visit as many tiles as possible, and print one valid route.",
        "aliases": [(1729, "C", 820, "Div. 3")],
    },
    {
        "key": "1472D",
        "title": "Even-Odd Game",
        "rating": 1200,
        "contest_time": 1609770900,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1472/problem/D",
        "clue": "Alice and Bob alternately erase one number from an array, with Alice moving first. Alice adds an erased number to her score only when it is even; Bob scores only when it is odd. Both play optimally. Determine whether Alice wins, Bob wins, or the game ends in a tie.",
        "aliases": [(1472, "D", 693, "Div. 3")],
    },
    {
        "key": "1922C",
        "title": "Closest Cities",
        "rating": 1300,
        "contest_time": 1705588500,
        "round_type": "Edu",
        "source_url": "https://codeforces.com/contest/1922/problem/C",
        "clue": "Cities lie at distinct integer coordinates on a line. Every city has a unique closest city. A trip to that closest city costs one coin; a direct trip to any other city costs the coordinate distance. For each ordered pair in the queries, find the minimum travel cost from the first city to the second.",
        "aliases": [(1922, "C", 161, "Edu")],
    },
    {
        "key": "1768C",
        "title": "Elemental Decompress",
        "rating": 1300,
        "contest_time": 1672929300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/1768/problem/C",
        "clue": "For an array a of length n, construct two permutations p and q of 1 through n such that max(p_i, q_i) equals a_i for every position. If this is impossible, print NO; otherwise print both permutations. Every value in the given array is between 1 and n.",
        "aliases": [(1768, "C", 842, "Div. 2")],
    },
    {
        "key": "1705C",
        "title": "Mark and His Unfinished Essay",
        "rating": 1400,
        "contest_time": 1657892100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/1705/problem/C",
        "clue": "Begin with a short lowercase string. Each operation appends a copy of one specified substring of the current text, so the conceptual final string may become extremely long. For every query position k, output the character at position k without constructing the whole expanded string.",
        "aliases": [(1705, "C", 807, "Div. 2")],
    },
    {
        "key": "1798C",
        "title": "Candy Store",
        "rating": 1700,
        "contest_time": 1679841300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/1798/problem/C",
        "clue": "Candies arrive in order. The i-th type has a_i candies whose total price is a_i times b_i. Divide the sequence into the fewest contiguous groups so that one positive price per individual candy can be chosen for each group and the total price of every type in that group is an integer multiple of that common price.",
        "aliases": [(1798, "C", 860, "Div. 2")],
    },
    {
        "key": "1881F",
        "title": "Minimum Maximum Distance",
        "rating": 1700,
        "contest_time": 1697121300,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1881/problem/F",
        "clue": "A tree has n vertices and exactly k of them are marked. Choose a vertex that minimizes the maximum graph distance from it to any marked vertex. Print that minimum possible maximum distance for every test case. The sum of n over all tests is bounded.",
        "aliases": [(1881, "F", 903, "Div. 3")],
    },
    {
        "key": "1941G",
        "title": "Rudolf and Subway",
        "rating": 2000,
        "contest_time": 1710167700,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1941/problem/G",
        "clue": "An undirected graph represents subway stations and tracks. Every edge has a color, and all edges of one color belong to the same line. Moving along a line is free after boarding it, but boarding another line counts again. Find the minimum number of lines needed to travel from station b to station e.",
        "aliases": [(1941, "G", 933, "Div. 3")],
    },
    {
        "key": "2264E2",
        "title": "A Prime Flood (Hard Version)",
        "rating": 2700,
        "contest_time": 1789319100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2264/problem/E2",
        "clue": "For every non-empty subsequence b of an array, repeatedly choose a prime p and simultaneously decrease by one each current element divisible by p. Let f(b) be the largest common value all elements can reach. Sum f(b) over all index-distinct subsequences modulo 998244353. In this hard version, n is at most 300000 and every a_i is at most n.",
        "aliases": [(2264, "E2", 1121, "Div. 2")],
    },
    {
        "key": "2268C",
        "title": "KiaKio and Energy Intervals",
        "rating": 2400,
        "contest_time": 1790433300,
        "round_type": "Div. 1 / Div. 2",
        "source_url": "https://codeforces.com/contest/2269/problem/E",
        "clue": "Choose a segment [l, r] of an integer array with l < r, and let m be the maximum element in that segment. Mask every segment element with m using bitwise AND, then combine all masked values using bitwise XOR. Over all valid segments, maximize the resulting energy. Values are below 2^18 and the total n is at most 200000.",
        "aliases": [
            (2268, "C", 1124, "Div. 1"),
            (2269, "E", 1124, "Div. 2"),
        ],
    },
]
