"""Curated seed questions.

The clue text is an original, title-free restatement of each public problem.  It
is deliberately long enough to uniquely identify a problem, while avoiding the
answer-bearing title and contest metadata.
"""

SEED_QUESTIONS = [
    {
        "key": "1328A",
        "title": "Divisibility Problem",
        "rating": 800,
        "contest_time": 1585233300,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1328/problem/A",
        "clue": "You are given two positive integers a and b. In one move you may increase a by 1. Find the minimum number of moves needed to make a divisible by b. Each test contains many independent pairs; both values are at most 10^9.",
        "aliases": [(1328, "A", 629, "Div. 3")],
    },
    {
        "key": "1547C",
        "title": "Pair Programming",
        "rating": 1100,
        "contest_time": 1625927700,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1547/problem/C",
        "clue": "Two programmers made separate logs of changes to the same file. A zero in a log adds a new line to the file; a positive number x edits line x and is valid only when x is not greater than the current number of lines. Merge both logs without changing the order inside either log, or report that no valid merge exists.",
        "aliases": [(1547, "C", 731, "Div. 3")],
    },
    {
        "key": "1729C",
        "title": "Jumping on Tiles",
        "rating": 1100,
        "contest_time": 1662993300,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1729/problem/C",
        "clue": "A row of tiles is described by a lowercase string. The price of a tile equals its letter position in the alphabet. Starting at the first tile, reach the last tile; the cost of a jump is the absolute difference between the prices of its endpoints. Minimize total cost, then visit as many tiles as possible, and print one valid route.",
        "aliases": [(1729, "C", 820, "Div. 3")],
    },
    {
        "key": "1472D",
        "title": "Even-Odd Game",
        "rating": 1200,
        "contest_time": 1609770900,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1472/problem/D",
        "clue": "Alice and Bob alternately erase one number from an array, with Alice moving first. Alice adds an erased number to her score only when it is even; Bob scores only when it is odd. Both play optimally. Determine whether Alice wins, Bob wins, or the game ends in a tie.",
        "aliases": [(1472, "D", 693, "Div. 3")],
    },
    {
        "key": "1922C",
        "title": "Closest Cities",
        "rating": 1300,
        "contest_time": 1705588500,
        "round_type": "Edu",
        "source_url": "https://codeforces.com/contest/1922/problem/C",
        "clue": "Cities lie at distinct integer coordinates on a line. Every city has a unique closest city. A trip to that closest city costs one coin; a direct trip to any other city costs the coordinate distance. For each ordered pair in the queries, find the minimum travel cost from the first city to the second.",
        "aliases": [(1922, "C", 161, "Edu")],
    },
    {
        "key": "1768C",
        "title": "Elemental Decompress",
        "rating": 1300,
        "contest_time": 1672929300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/1768/problem/C",
        "clue": "For an array a of length n, construct two permutations p and q of 1 through n such that max(p_i, q_i) equals a_i for every position. If this is impossible, print NO; otherwise print both permutations. Every value in the given array is between 1 and n.",
        "aliases": [(1768, "C", 842, "Div. 2")],
    },
    {
        "key": "1705C",
        "title": "Mark and His Unfinished Essay",
        "rating": 1400,
        "contest_time": 1657892100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/1705/problem/C",
        "clue": "Begin with a short lowercase string. Each operation appends a copy of one specified substring of the current text, so the conceptual final string may become extremely long. For every query position k, output the character at position k without constructing the whole expanded string.",
        "aliases": [(1705, "C", 807, "Div. 2")],
    },
    {
        "key": "1798C",
        "title": "Candy Store",
        "rating": 1700,
        "contest_time": 1679841300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/1798/problem/C",
        "clue": "Candies arrive in order. The i-th type has a_i candies whose total price is a_i times b_i. Divide the sequence into the fewest contiguous groups so that one positive price per individual candy can be chosen for each group and the total price of every type in that group is an integer multiple of that common price.",
        "aliases": [(1798, "C", 860, "Div. 2")],
    },
    {
        "key": "1881F",
        "title": "Minimum Maximum Distance",
        "rating": 1700,
        "contest_time": 1697121300,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1881/problem/F",
        "clue": "A tree has n vertices and exactly k of them are marked. Choose a vertex that minimizes the maximum graph distance from it to any marked vertex. Print that minimum possible maximum distance for every test case. The sum of n over all tests is bounded.",
        "aliases": [(1881, "F", 903, "Div. 3")],
    },
    {
        "key": "1941G",
        "title": "Rudolf and Subway",
        "rating": 2000,
        "contest_time": 1710167700,
        "round_type": "Div. 3",
        "source_url": "https://codeforces.com/contest/1941/problem/G",
        "clue": "An undirected graph represents subway stations and tracks. Every edge has a color, and all edges of one color belong to the same line. Moving along a line is free after boarding it, but boarding another line counts again. Find the minimum number of lines needed to travel from station b to station e.",
        "aliases": [(1941, "G", 933, "Div. 3")],
    },
    {
        "key": "2264E2",
        "title": "A Prime Flood (Hard Version)",
        "rating": 2700,
        "contest_time": 1789319100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2264/problem/E2",
        "clue": "For every non-empty subsequence b of an array, repeatedly choose a prime p and simultaneously decrease by one each current element divisible by p. Let f(b) be the largest common value all elements can reach. Sum f(b) over all index-distinct subsequences modulo 998244353. In this hard version, n is at most 300000 and every a_i is at most n.",
        "aliases": [(2264, "E2", 1121, "Div. 2")],
    },
    {
        "key": "2268C",
        "title": "KiaKio and Energy Intervals",
        "rating": 2400,
        "contest_time": 1790433300,
        "round_type": "Div. 1 / Div. 2",
        "source_url": "https://codeforces.com/contest/2269/problem/E",
        "clue": "Choose a segment [l, r] of an integer array with l < r, and let m be the maximum element in that segment. Mask every segment element with m using bitwise AND, then combine all masked values using bitwise XOR. Over all valid segments, maximize the resulting energy. Values are below 2^18 and the total n is at most 200000.",
        "aliases": [
            (2268, "C", 1124, "Div. 1"),
            (2269, "E", 1124, "Div. 2"),
        ],
    },
    {
        "key": "2194A",
        "title": "Lawn Mower",
        "rating": 800,
        "contest_time": 1770541500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2194/problem/A",
        "clue": "A cropped illustration shows fence-like strips between two brown borders, with selected vertical boards filled in beige and the remaining candidate positions drawn as dashed outlines.",
        "clue_kind": "image",
        "image_path": "static/questions/2194A.png",
        "aliases": [(2194, "A", 1078, "Div. 2")],
    },
    {
        "key": "2215B",
        "title": "RReeppeettiittiioonn",
        "rating": 2000,
        "contest_time": 1775972100,
        "round_type": "Div. 1 / Div. 2",
        "source_url": "https://codeforces.com/contest/2215/problem/B",
        "clue": "A tiny, highly distinctive text crop containing only the token C++ in large black type on a white background.",
        "clue_kind": "fragment",
        "image_path": "static/questions/2215B.png",
        "aliases": [
            (2215, "B", 1092, "Div. 1"),
            (2216, "D", 1092, "Div. 2"),
        ],
    },
    {
        "key": "2216B",
        "title": "THU Packing Puzzle",
        "rating": 1300,
        "contest_time": 1775972100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2216/problem/B",
        "clue": "A cropped packing diagram with a black L-shaped region, two stacked white rectangles, and thin black guide lines extending above them.",
        "clue_kind": "image",
        "image_path": "static/questions/2216B.png",
        "aliases": [(2216, "B", 1092, "Div. 2")],
    },
    {
        "key": "2232D",
        "title": "Magical Tiered Cake",
        "rating": 2000,
        "contest_time": 1780151700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2232/problem/D",
        "clue": "An intentionally extreme crop: a pink horizontal band above a black field, with only part of a thin white curved outline visible near the bottom edge.",
        "clue_kind": "image",
        "image_path": "static/questions/2232D.png",
        "brain": 1,
        "aliases": [(2232, "D", 1101, "Div. 2")],
    },
    {
        "key": "2257D@image01",
        "title": "Bermuda Rectangle",
        "rating": 1600,
        "contest_time": 1786977300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2257/problem/D",
        "clue": "A 57 by 57 pixel crop showing a pale gray-blue square divided by one horizontal and one vertical blue line near the lower-right region.",
        "clue_kind": "image",
        "image_path": "static/questions/2257D-01.png",
        "aliases": [(2257, "D", 1117, "Div. 2")],
    },
    {
        "key": "2268F@image01",
        "title": "Deglado",
        "rating": 3500,
        "contest_time": 1790433300,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/2268/problem/F",
        "clue": "An extreme crop containing two adjacent outlined cells: a white cell labeled 1 and a muted red cell labeled 3, separated by a thick black border.",
        "clue_kind": "image",
        "image_path": "static/questions/2268F-01.png",
        "brain": 1,
        "aliases": [(2268, "F", 1124, "Div. 1")],
    },
    {
        "key": "2245E@image01",
        "title": "Tom and Jerry",
        "rating": 2300,
        "contest_time": 1784213100,
        "round_type": "Div. 1 + Div. 2",
        "source_url": "https://codeforces.com/contest/2245/problem/E",
        "clue": "An extreme narrow vertical crop containing two partial occurrences of the word On and two columns of isolated black bullet points on a white background.",
        "clue_kind": "image",
        "image_path": "static/questions/2245E-01.png",
        "brain": 1,
        "aliases": [(2245, "E", 1110, "Div. 1 + Div. 2")],
    },
    {
        "key": "2223B@image01",
        "title": "Zhily and Barknights",
        "rating": 1600,
        "contest_time": 1778047500,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/2223/problem/B",
        "clue": "An extreme 327 by 90 pixel crop of a sparse table: the bottoms of 25 and 1 appear in the upper row, 10 and 0 in the lower row, separated by thin gray grid lines.",
        "clue_kind": "image",
        "image_path": "static/questions/2223B-01.png",
        "brain": 1,
        "aliases": [(2223, "B", 1097, "Div. 1")],
    },
    {
        "key": "2242E@image01",
        "title": "Product of Closures",
        "rating": 2200,
        "contest_time": 1783348500,
        "round_type": "Edu",
        "source_url": "https://codeforces.com/contest/2242/problem/E",
        "clue": "An extreme crop of a mathematical diagram showing C(4) and C(9), binary strings joined by an ampersand, a horizontal rule, and a third binary result below.",
        "clue_kind": "image",
        "image_path": "static/questions/2242E-01.png",
        "brain": 1,
        "aliases": [(2242, "E", 192, "Edu")],
    },
    {
        "key": "1677B@image01",
        "title": "Tokitsukaze and Meeting",
        "rating": 1700,
        "contest_time": 1652020500,
        "round_type": "Div. 1 / Div. 2",
        "source_url": "https://codeforces.com/contest/1677/problem/B",
        "clue": "A narrow crop of two vertically stacked grid cells labeled 0 (4th student) and 1 (2nd student), with a thin gray border and serif annotations.",
        "clue_kind": "image",
        "image_path": "static/questions/1677B-01.png",
        "brain": 1,
        "aliases": [
            (1677, "B", 789, "Div. 1"),
            (1678, "D", 789, "Div. 2"),
        ],
    },
    {
        "key": "2258D@image01",
        "title": "Magic Tiles",
        "rating": 2500,
        "contest_time": 1788014100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2258/problem/D",
        "clue": "A small formula crop containing a summation from i equals 1 to k and the term 100 raised to a power involving 100 and x sub i.",
        "clue_kind": "image",
        "image_path": "static/questions/2258D-01.png",
        "brain": 1,
        "aliases": [(2258, "D", 1118, "Div. 2")],
    },
    {
        "key": "2256E@image01",
        "title": "Even If the World Turns",
        "rating": 2100,
        "contest_time": 1786286100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2256/problem/E",
        "clue": "A single bold statement line saying that gcd of n and w is guaranteed to equal 1.",
        "clue_kind": "image",
        "image_path": "static/questions/2256E-01.png",
        "brain": 1,
        "aliases": [(2256, "E", 1116, "Div. 2")],
    },
    {
        "key": "2238C@image01",
        "title": "Village Guilds",
        "rating": 1400,
        "contest_time": 1782657300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2238/problem/C",
        "clue": "An extremely narrow graph crop with a red circular node labeled 2 above a white circular node labeled 3, joined by a vertical black edge.",
        "clue_kind": "image",
        "image_path": "static/questions/2238C-01.png",
        "brain": 1,
        "aliases": [(2238, "C", 1106, "Div. 2")],
    },
    {
        "key": "2247E@image01",
        "title": "Build a Tree",
        "rating": 2300,
        "contest_time": 1784385300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2247/problem/E",
        "clue": "A sparse four-node tree diagram where central node 1 connects to nodes 3, 4, and 2 in three different directions.",
        "clue_kind": "image",
        "image_path": "static/questions/2247E-01.png",
        "brain": 1,
        "aliases": [(2247, "E", 1111, "Div. 2")],
    },
    {
        "key": "2238E@image01",
        "title": "Cake Trial",
        "rating": 2100,
        "contest_time": 1782657300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2238/problem/E",
        "clue": "An extreme text crop showing only the right-hand fragments of three short lines containing cake is, cake is, and no cake.",
        "clue_kind": "image",
        "image_path": "static/questions/2238E-01.png",
        "brain": 1,
        "aliases": [(2238, "E", 1106, "Div. 2")],
    },
    {
        "key": "2246E@image01",
        "title": "lce4113 and Security Game",
        "rating": 2600,
        "contest_time": 1783866900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2246/problem/E",
        "clue": "A two-line interactive-problem note stating that the interactor is partially adaptive and that values will be fixed afterward.",
        "clue_kind": "image",
        "image_path": "static/questions/2246E-01.png",
        "brain": 1,
        "aliases": [(2246, "E", 1108, "Div. 2")],
    },
    {
        "key": "2194D@image01",
        "title": "Table Cut",
        "rating": 1600,
        "contest_time": 1770541500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2194/problem/D",
        "clue": "A cropped two-by-two binary table with 1 1 above 0 0 and a thick red stair-step cut passing between the cells.",
        "clue_kind": "image",
        "image_path": "static/questions/2194D-01.png",
        "brain": 1,
        "aliases": [(2194, "D", 1078, "Div. 2")],
    },
    {
        "key": "2197C@image01",
        "title": "Game with a Fraction",
        "rating": 1200,
        "contest_time": 1770820500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2197/problem/C",
        "clue": "A two-row monospace output crop containing very long red integers, including a row beginning with 7 followed by many zeroes and another beginning with 1.",
        "clue_kind": "image",
        "image_path": "static/questions/2197C-01.png",
        "brain": 1,
        "aliases": [(2197, "C", 1079, "Div. 2")],
    },
    {
        "key": "2175E1@image01",
        "title": "Beautiful Patterns",
        "rating": 2400,
        "contest_time": 1765008900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2175/problem/E1",
        "clue": "A compact worked formula summing four squared fractions over 4 and evaluating the result as 13 times the inverse of 2 modulo 101, equal to 57.",
        "clue_kind": "image",
        "image_path": "static/questions/2175E1-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (2175, "E1", 1069, "Div. 2"),
            (2175, "E2", 1069, "Div. 2"),
        ],
    },
    {
        "key": "2166D@image01",
        "title": "Marble Council",
        "rating": 1900,
        "contest_time": 1763303700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2166/problem/D",
        "clue": "A tiny rule fragment reading choose one of its modes followed by an asterisk, with one and modes emphasized in bold.",
        "clue_kind": "image",
        "image_path": "static/questions/2166D-01.png",
        "brain": 1,
        "aliases": [(2166, "D", 1064, "Div. 2")],
    },
    {
        "key": "2156B@image01",
        "title": "Strange Machine",
        "rating": 1000,
        "contest_time": 1761316500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2156/problem/B",
        "clue": "An extremely narrow vertical crop of several floor expressions with numerators 20, 10, 5, 2, and 1 divided by 2.",
        "clue_kind": "image",
        "image_path": "static/questions/2156B-01.png",
        "brain": 1,
        "aliases": [(2156, "B", 1061, "Div. 2")],
    },
    {
        "key": "2224E@image01",
        "title": "Zhily and Signpost",
        "rating": 2300,
        "contest_time": 1778047500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2224/problem/E",
        "clue": "A cropped graph diagram with three vertical pairs of circular nodes labeled 3 over 8, 4 over 9, and 5 over 10, with edge labels 7, 8, and 9.",
        "clue_kind": "image",
        "image_path": "static/questions/2224E-01.png",
        "brain": 1,
        "aliases": [(2224, "E", 1097, "Div. 2")],
    },
    {
        "key": "2226C@image01",
        "title": "Mental Monumental",
        "rating": 1500,
        "contest_time": 1777386900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2226/problem/C",
        "clue": "A long one-line footnote defining mex as the minimum excluded integer and giving the examples mex of [2,2,1] equals 0 and mex of [0,3,1,2] equals 4.",
        "clue_kind": "image",
        "image_path": "static/questions/2226C-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (2226, "C", 1095, "Div. 2"),
            (2226, "E", 1095, "Div. 2"),
        ],
    },
    {
        "key": "2226C@image02",
        "title": "Mental Monumental (Easy Version)",
        "rating": 1500,
        "contest_time": 1777386900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2226/problem/C",
        "clue": "A cropped problem list with blurred titles for Easy and Hard Version, where a red arrow explicitly points to the Easy Version label.",
        "clue_kind": "image",
        "image_path": "static/questions/2226C-02.png",
        "brain": 1,
        "aliases": [(2226, "C", 1095, "Div. 2")],
    },
    {
        "key": "2216D@image01",
        "title": "RReeppeettiittiioonn",
        "rating": 2000,
        "contest_time": 1775972100,
        "round_type": "Div. 1 / Div. 2",
        "source_url": "https://codeforces.com/contest/2216/problem/D",
        "clue": "A tiny three-row monospace output crop in dark red, containing the digit rows 1111, 2233, and 3355.",
        "clue_kind": "image",
        "image_path": "static/questions/2216D-01.png",
        "brain": 1,
        "aliases": [
            (2215, "B", 1092, "Div. 1"),
            (2216, "D", 1092, "Div. 2"),
        ],
    },
    {
        "key": "2209C@image01",
        "title": "Find the Zero",
        "rating": 1400,
        "contest_time": 1774103700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2209/problem/C",
        "clue": "A single interactive-problem sentence saying the interactor is adaptive and that the hidden array a may change.",
        "clue_kind": "image",
        "image_path": "static/questions/2209C-01.png",
        "brain": 1,
        "aliases": [(2209, "C", 1087, "Div. 2")],
    },
    {
        "key": "2210B@image01",
        "title": "Permutation Definition",
        "rating": 900,
        "contest_time": 1774794900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2210/problem/B",
        "clue": "A long footnote defining a permutation of length n and giving [2,3,1,5,4], [1,2,2], and [1,3,4] as examples and counterexamples.",
        "clue_kind": "image",
        "image_path": "static/questions/2210B-01.png",
        "brain": 1,
        "open_mode": 1,
        "verification_text": "The same permutation-definition footnote occurs in 2210A, 2210B, 2205D, and 2217E.",
        "aliases": [
            (2210, "A", 1089, "Div. 2"),
            (2210, "B", 1089, "Div. 2"),
            (2205, "D", 1083, "Div. 2"),
            (2217, "E", 1091, "Div. 2"),
        ],
    },
    {
        "key": "2210B@image02",
        "title": "Permutation Definition",
        "rating": 900,
        "contest_time": 1774794900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2210/problem/B",
        "clue": "A wider crop of the same permutation-definition footnote, including its top rule and the beginning of the Input heading below.",
        "clue_kind": "image",
        "image_path": "static/questions/2210B-02.png",
        "brain": 1,
        "open_mode": 1,
        "verification_text": "The same permutation-definition footnote occurs in 2210A, 2210B, 2205D, and 2217E.",
        "aliases": [
            (2210, "A", 1089, "Div. 2"),
            (2210, "B", 1089, "Div. 2"),
            (2205, "D", 1083, "Div. 2"),
            (2217, "E", 1091, "Div. 2"),
        ],
    },
    {
        "key": "2210A@image01",
        "title": "Permutation Definition",
        "rating": 800,
        "contest_time": 1774794900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2210/problem/A",
        "clue": "A very small crop of the permutation-definition footnote with its rule line and the standard examples and counterexamples.",
        "clue_kind": "image",
        "image_path": "static/questions/2210A-01.png",
        "brain": 1,
        "open_mode": 1,
        "verification_text": "The same permutation-definition footnote occurs in 2210A, 2210B, 2205D, and 2217E.",
        "aliases": [
            (2210, "A", 1089, "Div. 2"),
            (2210, "B", 1089, "Div. 2"),
            (2205, "D", 1083, "Div. 2"),
            (2217, "E", 1091, "Div. 2"),
        ],
    },
    {
        "key": "2197E1@image01",
        "title": "Interactive Graph",
        "rating": 1800,
        "contest_time": 1770820500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2197/problem/E1",
        "clue": "A five-node directed acyclic graph where node 1 points to 2 and 3, and those nodes point across to nodes 4 and 5.",
        "clue_kind": "image",
        "image_path": "static/questions/2197E1-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (2197, "E1", 1079, "Div. 2"),
            (2197, "E2", 1079, "Div. 2"),
        ],
    },
    {
        "key": "2208D2@image01",
        "title": "Tree Orientation (Hard Version)",
        "rating": 2200,
        "contest_time": 1773498900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2208/problem/D2",
        "clue": "A single constraint line guaranteeing that the sum of n squared over all test cases does not exceed 8000 squared.",
        "clue_kind": "image",
        "image_path": "static/questions/2208D2-01.png",
        "brain": 1,
        "aliases": [(2208, "D2", 1086, "Div. 2")],
    },
    {
        "key": "2119A@image01",
        "title": "Add or XOR",
        "rating": 800,
        "contest_time": 1751726100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2119/problem/A",
        "clue": "A tiny blue italic crop reading r-906 ampersand IA AI followed by the truncated phrase Psychologic Disco.",
        "clue_kind": "image",
        "image_path": "static/questions/2119A-01.png",
        "brain": 1,
        "aliases": [(2119, "A", 1035, "Div. 2")],
    },
    {
        "key": "2128B@image01",
        "title": "Deque Process",
        "rating": 1100,
        "contest_time": 1753626900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2128/problem/B",
        "clue": "A small two-line array example with selected entries in red, showing [3,1,2,4,5,6] and [7,6,5,4,1,2,3].",
        "clue_kind": "image",
        "image_path": "static/questions/2128B-01.png",
        "brain": 1,
        "aliases": [(2128, "B", 1039, "Div. 2")],
    },
    {
        "key": "2120B@image01",
        "title": "Square Pool",
        "rating": 1000,
        "contest_time": 1750516500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2120/problem/B",
        "clue": "A coordinate diagram with orange and red arrows around a mouse pointer and the labels (1.5, 2.5) and (2.5, 1.5).",
        "clue_kind": "image",
        "image_path": "static/questions/2120B-01.png",
        "brain": 1,
        "aliases": [(2120, "B", 1033, "Div. 2")],
    },
    {
        "key": "2234D@image01",
        "title": "XOR, Expression and Two Binary Numbers",
        "rating": 1500,
        "contest_time": 1780842900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2234/problem/D",
        "clue": "A cropped mathematical assignment defining an indexed a term as the XOR of two other indexed a terms.",
        "clue_kind": "image",
        "image_path": "static/questions/2234D-01.png",
        "brain": 1,
        "aliases": [(2234, "D", 1102, "Div. 2")],
    },
    {
        "key": "2232B@image01",
        "title": "Cake Leveling",
        "rating": 900,
        "contest_time": 1780151700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2232/problem/B",
        "clue": "A cropped sample with red numeric input and output, where the central output is rendered as several rows of pale red pixel-like blocks.",
        "clue_kind": "image",
        "image_path": "static/questions/2232B-01.png",
        "brain": 1,
        "aliases": [(2232, "B", 1101, "Div. 2")],
    },
    {
        "key": "2130E3@image01",
        "title": "Interactive RBS (Hard Version)",
        "rating": 2300,
        "contest_time": 1753972500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2130/problem/E3",
        "clue": "A cropped three-row problem list for E1 Easy, E2 Medium, and E3 Hard, with a red arrow explicitly pointing at E3.",
        "clue_kind": "image",
        "image_path": "static/questions/2130E3-01.png",
        "brain": 1,
        "aliases": [(2130, "E3", 1040, "Div. 2")],
    },
    {
        "key": "2139E1@image01",
        "title": "Maple and Tree Beauty",
        "rating": 1800,
        "contest_time": 1757342100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2139/problem/E1",
        "clue": "A cropped tree diagram showing nodes 2 above 4 and nodes 3 above 5, with the binary label 101 under both lower nodes.",
        "clue_kind": "image",
        "image_path": "static/questions/2139E1-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (2139, "E1", 1048, "Div. 2"),
            (2139, "E2", 1048, "Div. 2"),
        ],
    },
    {
        "key": "2151G1@image01",
        "title": "Hidden Single",
        "rating": 2600,
        "contest_time": 1758713700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2151/problem/G1",
        "clue": "A large crop of standard interactive instructions covering malformed queries, flushing output in several languages, and a non-adaptive interactor.",
        "clue_kind": "image",
        "image_path": "static/questions/2151G1-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (2151, "G1", 1053, "Div. 2"),
            (2151, "G2", 1053, "Div. 2"),
        ],
    },
    {
        "key": "2151D@image01",
        "title": "Grid Counting",
        "rating": 1700,
        "contest_time": 1758713700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2151/problem/D",
        "clue": "A narrow interactive transcript table headed Solution and Jury, with question and exclamation commands beside numeric jury responses.",
        "clue_kind": "image",
        "image_path": "static/questions/2151D-01.png",
        "brain": 1,
        "aliases": [(2151, "D", 1053, "Div. 2")],
    },
    {
        "key": "2151A@image01",
        "title": "Incremental Subarray",
        "rating": 800,
        "contest_time": 1758713700,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2151/problem/A",
        "clue": "A tiny blue italic text fragment reading Schtiffles - Marbl with the last word cut off.",
        "clue_kind": "image",
        "image_path": "static/questions/2151A-01.png",
        "brain": 1,
        "aliases": [(2151, "A", 1053, "Div. 2")],
    },
    {
        "key": "2146D1@image01",
        "title": "Max Sum OR",
        "rating": 1500,
        "contest_time": 1758465300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2146/problem/D1",
        "clue": "A single worked expression summing four bitwise-OR pairs, each equal to 3, for a total of 12.",
        "clue_kind": "image",
        "image_path": "static/questions/2146D1-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (2146, "D1", 1052, "Div. 2"),
            (2146, "D2", 1052, "Div. 2"),
        ],
    },
    {
        "key": "2156D@image01",
        "title": "Find the Last Number",
        "rating": 1900,
        "contest_time": 1761316500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2156/problem/D",
        "clue": "A tall narrow Solution versus Jury interaction table containing commands such as question 1 1, question 1 2, and exclamation 2.",
        "clue_kind": "image",
        "image_path": "static/questions/2156D-01.png",
        "brain": 1,
        "aliases": [(2156, "D", 1061, "Div. 2")],
    },
    {
        "key": "2110F@image01",
        "title": "Faculty",
        "rating": 2400,
        "contest_time": 1748097300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2110/problem/F",
        "clue": "A cropped worked sequence where successive lines evaluate f of pairs such as f(3,1), f(3,4), f(4,3), and f(4,5).",
        "clue_kind": "image",
        "image_path": "static/questions/2110F-01.png",
        "brain": 1,
        "aliases": [(2110, "F", 1026, "Div. 2")],
    },
    {
        "key": "2120G@image01",
        "title": "Eulerian Line Graph",
        "rating": 3000,
        "contest_time": 1750516500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2120/problem/G",
        "clue": "A colored five-node graph with pale green edge labels such as 1-2 and 4-5 and several dashed green loops.",
        "clue_kind": "image",
        "image_path": "static/questions/2120G-01.png",
        "brain": 1,
        "aliases": [(2120, "G", 1033, "Div. 2")],
    },
    {
        "key": "2120G@image02",
        "title": "Eulerian Line Graph",
        "rating": 3000,
        "contest_time": 1750516500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2120/problem/G",
        "clue": "A six-node black line graph whose circular vertices are labeled by pairs 1-2, 2-3, 1-3, 3-4, 4-5, and 5-1.",
        "clue_kind": "image",
        "image_path": "static/questions/2120G-02.png",
        "brain": 1,
        "aliases": [(2120, "G", 1033, "Div. 2")],
    },
    {
        "key": "2113E@image01",
        "title": "From Kazan with Love",
        "rating": 2800,
        "contest_time": 1749978300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2113/problem/E",
        "clue": "A tiny bold sentence fragment reading can no longer meet him.",
        "clue_kind": "image",
        "image_path": "static/questions/2113E-01.png",
        "brain": 1,
        "aliases": [(2113, "E", 1031, "Div. 2")],
    },
    {
        "key": "2113C@image01",
        "title": "Smilo and Minecraft",
        "rating": 1700,
        "contest_time": 1749978300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2113/problem/C",
        "clue": "A cropped two-by-three Minecraft-style grid containing dark blocks, gold ingots, and a TNT block on a red central cell.",
        "clue_kind": "image",
        "image_path": "static/questions/2113C-01.png",
        "brain": 1,
        "aliases": [(2113, "C", 1031, "Div. 2")],
    },
    {
        "key": "2119C@image01",
        "title": "A Good Problem",
        "rating": 1300,
        "contest_time": 1751726100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2119/problem/C",
        "clue": "A cropped sample containing very large values made from long runs of 9s and 0s, plus the number 1.",
        "clue_kind": "image",
        "image_path": "static/questions/2119C-01.png",
        "brain": 1,
        "aliases": [(2119, "C", 1035, "Div. 2")],
    },
    {
        "key": "2120D@image01",
        "title": "Matrix game",
        "rating": 1800,
        "contest_time": 1750516500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2120/problem/D",
        "clue": "A 3 by 3 matrix transformed into an all-ones 2 by 2 matrix by removing its second row and then its second column.",
        "clue_kind": "image",
        "image_path": "static/questions/2120D-01.png",
        "brain": 1,
        "aliases": [(2120, "D", 1033, "Div. 2")],
    },
    {
        "key": "2134D@image01",
        "title": "Sliding Tree",
        "rating": 2300,
        "contest_time": 1756218900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2134/problem/D",
        "clue": "A tiny crop of a tree diagram showing vertices 1 and 6 inside the same pale yellow highlighted region.",
        "clue_kind": "image",
        "image_path": "static/questions/2134D-01.png",
        "brain": 1,
        "aliases": [(2134, "D", 1045, "Div. 2")],
    },
    {
        "key": "2133C@image01",
        "title": "The Nether",
        "rating": 1400,
        "contest_time": 1756046100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2133/problem/C",
        "clue": "A five-node directed graph with purple square vertices and arrows pointing toward vertices 1, 2, and 4.",
        "clue_kind": "image",
        "image_path": "static/questions/2133C-01.png",
        "brain": 1,
        "aliases": [(2133, "C", 1044, "Div. 2")],
    },
    {
        "key": "2133E@image01",
        "title": "I Yearned For The Mines",
        "rating": 2500,
        "contest_time": 1756046100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2133/problem/E",
        "clue": "A single output constraint requiring an integer k between 1 and the floor of five quarters times n.",
        "clue_kind": "image",
        "image_path": "static/questions/2133E-01.png",
        "brain": 1,
        "aliases": [(2133, "E", 1044, "Div. 2")],
    },
    {
        "key": "2153B@image01",
        "title": "Bitwise Reversion",
        "rating": 800,
        "contest_time": 1760106900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2153/problem/B",
        "clue": "Three bullet-point bitwise equations: a AND b equals x, b AND c equals y, and a AND c equals z.",
        "clue_kind": "image",
        "image_path": "static/questions/2153B-01.png",
        "brain": 1,
        "aliases": [(2153, "B", 1057, "Div. 2")],
    },
    {
        "key": "2154E@image01",
        "title": "No Mind To Think",
        "rating": 2500,
        "contest_time": 1760884500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2154/problem/E",
        "clue": "A sequence operation example changing [1,1,2,3,1,2] into [2,1,2,3,1,2].",
        "clue_kind": "image",
        "image_path": "static/questions/2154E-01.png",
        "brain": 1,
        "aliases": [(2154, "E", 1060, "Div. 2")],
    },
    {
        "key": "2155D@image01",
        "title": "Batteries",
        "rating": 1800,
        "contest_time": 1759682100,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2155/problem/D",
        "clue": "A small Participant versus Jury interaction table with responses 3, 0, and 1 to a dash and the pairs 1 2 and 2 3.",
        "clue_kind": "image",
        "image_path": "static/questions/2155D-01.png",
        "brain": 1,
        "aliases": [(2155, "D", 1056, "Div. 2")],
    },
    {
        "key": "2140B@image01",
        "title": "Another Divisibility Problem",
        "rating": 900,
        "contest_time": 1757428500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2140/problem/B",
        "clue": "A tall sample showing six numeric inputs such as 42, 1000, and 9876543 and six numeric outputs.",
        "clue_kind": "image",
        "image_path": "static/questions/2140B-01.png",
        "brain": 1,
        "aliases": [(2140, "B", 1049, "Div. 2")],
    },
    {
        "key": "2188G@image01",
        "title": "Doors and Keys",
        "rating": 3500,
        "contest_time": 1769697300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2188/problem/G",
        "clue": "The final bold word independent followed by the footnote defining a binary string as containing only 0 or 1.",
        "clue_kind": "image",
        "image_path": "static/questions/2188G-01.png",
        "brain": 1,
        "aliases": [(2188, "G", 1077, "Div. 2")],
    },
    {
        "key": "2189B@image01",
        "title": "The Curse of the Frog",
        "rating": 1200,
        "contest_time": 1769178900,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2189/problem/B",
        "clue": "A tiny cropped explanation fragment containing rollback arrows from 1 to 3 to 5 and a truncated rollback of 4.",
        "clue_kind": "image",
        "image_path": "static/questions/2189B-01.png",
        "brain": 1,
        "aliases": [(2189, "B", 1075, "Div. 2")],
    },
    {
        "key": "2173C@image01",
        "title": "Kanade's Perfect Multiples",
        "rating": 1400,
        "contest_time": 1764945300,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2173/problem/C",
        "clue": "A narrow crop of the Output section whose nested bullet list is mostly cut off on the right.",
        "clue_kind": "image",
        "image_path": "static/questions/2173C-01.png",
        "brain": 1,
        "aliases": [(2173, "C", 1068, "Div. 2")],
    },
    {
        "key": "2217G@image01",
        "title": "Down the Pivot",
        "rating": 2600,
        "contest_time": 1775572500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2217/problem/G",
        "clue": "Four disjoint two-node diagrams whose circular nodes contain combinations of 1 and 0.",
        "clue_kind": "image",
        "image_path": "static/questions/2217G-01.png",
        "brain": 1,
        "aliases": [(2217, "G", 1091, "Div. 2")],
    },
    {
        "key": "2135B@image01",
        "title": "For the Champion",
        "rating": 1700,
        "contest_time": 1756391700,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/2135/problem/B",
        "clue": "Four bullet points describing moves up, down, left, and right by k units.",
        "clue_kind": "image",
        "image_path": "static/questions/2135B-01.png",
        "brain": 1,
        "aliases": [(2135, "B", 1046, "Div. 1")],
    },
    {
        "key": "2138D@image01",
        "title": "Antiamuny and Slider Movement",
        "rating": 2600,
        "contest_time": 1757342100,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/2138/problem/D",
        "clue": "Four number-line diagrams demonstrating five numbered blocks sliding together, with the moved boundary block highlighted red.",
        "clue_kind": "image",
        "image_path": "static/questions/2138D-01.png",
        "brain": 1,
        "aliases": [(2138, "D", 1048, "Div. 1")],
    },
    {
        "key": "2205B@image01",
        "title": "Simons and Cakes for Success",
        "rating": 800,
        "contest_time": 1772116500,
        "round_type": "Div. 2",
        "source_url": "https://codeforces.com/contest/2205/problem/B",
        "clue": "A tiny mathematical crop showing a twelfth power equal to 2,176,782,336, with both sides partially cut off.",
        "clue_kind": "image",
        "image_path": "static/questions/2205B-01.png",
        "brain": 1,
        "aliases": [(2205, "B", 1083, "Div. 2")],
    },
    {
        "key": "2150D@image01",
        "title": "Attraction Theory",
        "rating": 2700,
        "contest_time": 1758713700,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/2150/problem/D",
        "clue": "A bullet list of eight nondecreasing triples ranging from [1,1,1] through [3,3,3].",
        "clue_kind": "image",
        "image_path": "static/questions/2150D-01.png",
        "brain": 1,
        "aliases": [(2150, "D", 1053, "Div. 1")],
    },
    {
        "key": "2262D@image01",
        "title": "PLUSworld",
        "rating": 2900,
        "contest_time": 1789223700,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/2262/problem/D",
        "clue": "A cropped red inequality involving i and b sub i above a constraint that the sum over test cases does not exceed 1000 squared.",
        "clue_kind": "image",
        "image_path": "static/questions/2262D-01.png",
        "brain": 1,
        "aliases": [(2262, "D", 1120, "Div. 1")],
    },
    {
        "key": "1874C@image01",
        "title": "Jellyfish and EVA",
        "rating": 2300,
        "contest_time": 1696084500,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/1874/problem/C",
        "clue": "A sample output crop containing the three decimal values 0.500000000000, 0.625000000000, and 0.491666666667.",
        "clue_kind": "image",
        "image_path": "static/questions/1874C-01.png",
        "brain": 1,
        "aliases": [(1874, "C", 901, "Div. 1")],
    },
    {
        "key": "1854B@image01",
        "title": "Earn or Unlock",
        "rating": 2200,
        "contest_time": 1690641300,
        "round_type": "Div. 1",
        "source_url": "https://codeforces.com/contest/1854/problem/B",
        "clue": "A pink visual-novel banner showing the stylized Tanto Cuore logo beside a blonde maid character.",
        "clue_kind": "image",
        "image_path": "static/questions/1854B-01.png",
        "brain": 1,
        "aliases": [(1854, "B", 889, "Div. 1")],
    },
    {
        "key": "1924B@image01",
        "title": "Space Harbour",
        "rating": 2100,
        "contest_time": 1706366700,
        "round_type": "Div. 1 / Div. 2",
        "source_url": "https://codeforces.com/contest/1924/problem/B",
        "clue": "A single bold guarantee that there are harbours at the points 1 and n.",
        "clue_kind": "image",
        "image_path": "static/questions/1924B-01.png",
        "brain": 1,
        "open_mode": 1,
        "aliases": [
            (1924, "B", 921, "Div. 1"),
            (1925, "E", 921, "Div. 2"),
        ],
    },
]

from .reviewed_search_clues import SEARCH_CLUES
SEED_QUESTIONS += SEARCH_CLUES
